spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pokiepaws}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pokiepaws}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pokiepaws0303}

server.port=${SERVER_PORT:9090}

app.admin.email=${ADMIN_EMAIL:admin@example.com}
app.admin.password=${ADMIN_PASSWORD:Admin123!}
app.admin.first-name=${ADMIN_FIRST_NAME:Admin}
app.admin.last-name=${ADMIN_LAST_NAME:User}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.properties.mail.debug=${MAIL_DEBUG:true}

app.base-url=${BASE_URL:http://localhost:9090}
app.frontend-url=${FRONTEND_URL:http://localhost:3000}

app.jwt.secret=${JWT_SECRET:41008870ef465954c6efa46898366c177e7bfe46475376a0459122bd9c63ef51b2a69538fcda053cd6f02cec5ad02dba009f031b39546ba0d0f2b1065288ae9f}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
app.data-init.enabled=${DATA_INIT_ENABLED:true}

server.error.include-message=${SERVER_ERROR_INCLUDE_MESSAGE:always}
server.error.include-binding-errors=${SERVER_ERROR_INCLUDE_BINDING_ERRORS:always}
logging.level.org.springframework.web=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:DEBUG}
logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:DEBUG}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_ORG_HIBERNATE_SQL:DEBUG}
logging.level.org.hibernate.orm.jdbc.bind=${LOGGING_LEVEL_ORG_HIBERNATE_ORM_JDBC_BIND:TRACE}
