spring.application.name=pokiepaws-api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.first-name=${ADMIN_FIRST_NAME}
app.admin.last-name=${ADMIN_LAST_NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAILPIT_SMTP_PORT}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.base-url=${BASE_URL}
app.frontend-url=${FRONTEND_URL}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}