package com.pokiepaws.api.dto.realtime;

public enum RealtimeEventType {
  VISIT_CREATED,
  VISIT_CANCELLED,
  VISIT_MEDICAL_DATA_UPDATED,
  PRESCRIPTION_CREATED,
  CLINIC_STOCK_UPDATED,
  ORDER_CREATED,
  ORDER_STATUS_UPDATED,
  ACTIVITY_LOG_CREATED,
  LAB_ORDER_CREATED,
  LAB_ORDER_STATUS_UPDATED
}
